// Shared UI pieces: app bar, language switcher, settings & premium dialogs,
// privacy page, restore-from-link page, footer.
import { h, iconBtn, btn, modal, toast, confirmDialog, downloadText, pickFile } from '../ui.js';
import { icon } from '../icons.js';
import { t, LANGS, LANG_NAMES, getLang, setLang, langUrl, fmtNum } from '../i18n.js';
import * as store from '../store.js';
import { toggleScheme, resolvedScheme, setThemePref } from '../theme.js';
import { isPremium, getLicense, activateLicense, removeLicense, hideAdsForSession, maskKey } from '../premium.js';
import { adsActive } from '../ads.js';
import { exportJson, parseImport, prepareImported, linkToBoard } from '../share.js';
import { parseSteps, normName, namesInBoard } from '../model.js';
import { APP_VERSION } from '../env.js';

const cfg = window.PUNKTO_CONFIG;

/** Landing pages (generated by tools/generate-pages.mjs from content/landing/). */
export const USE_CASES = ['scoreboard', 'leaderboard', 'classroom', 'quiz', 'score-keeper'];

/** Re-run the router (used after language/premium changes). */
export function reroute() { window.dispatchEvent(new HashChangeEvent('hashchange')); }

export const logoSvg = `<svg viewBox="0 0 512 512" class="logo" aria-hidden="true"><rect width="512" height="512" rx="120" fill="var(--accent)"/><path d="M190 386V136h88a78 78 0 0 1 0 156h-88" fill="none" stroke="var(--accent-ink)" stroke-width="58" stroke-linecap="round" stroke-linejoin="round"/><circle cx="356" cy="372" r="38" fill="var(--gold)"/></svg>`;

/* --------------------------------------------------------- point buttons */

/**
 * Text field for the point buttons, e.g. "1, 3" → [1, 3].
 * onChange receives the parsed list; invalid input snaps back to the last valid value.
 */
export function stepsInput(initial, onChange, label = t('settings.steps')) {
  let current = [...initial];
  const input = h('input.input', {
    type: 'text', value: current.join(', '), inputMode: 'numeric', 'aria-label': label,
    onchange: () => {
      const s = parseSteps(input.value);
      if (s.length) { current = s; onChange(s); }
      input.value = current.join(', ');
    }
  });
  input.getSteps = () => { const s = parseSteps(input.value); return s.length ? s : current; };
  return input;
}

/**
 * The "Point buttons" field: one input for adding, one for subtracting.
 * Returns { el, plus, minus } where plus/minus are stepsInput elements.
 */
export function stepsFields(plusInit, minusInit, onPlus = () => {}, onMinus = () => {}) {
  const plus = stepsInput(plusInit, onPlus, t('settings.stepsPlus'));
  const minus = stepsInput(minusInit, onMinus, t('settings.stepsMinus'));
  const el = h('div.field',
    h('span.field-label', { text: t('settings.steps') }),
    h('div.steps-fields',
      h('label.steps-field', h('span.steps-sign.plus', { text: '+', title: t('settings.stepsPlus') }), h('span.sr-only', { text: t('settings.stepsPlus') }), plus),
      h('label.steps-field', h('span.steps-sign.minus', { text: '−', title: t('settings.stepsMinus') }), h('span.sr-only', { text: t('settings.stepsMinus') }), minus)
    ),
    h('span.small.muted', { text: t('settings.stepsHint') })
  );
  return { el, plus, minus };
}

/* ---------------------------------------------------------- manual score */

/**
 * A score that can be clicked and typed over. Shows `value` as a button;
 * on click it turns into a number field. Enter or leaving the field calls
 * onSet(newValue) when the number changed; Escape cancels.
 */
export function editableScore({ value, label, onSet, cls = '', dataset = {} }) {
  const shown = fmtNum(value);
  const b = h('button.score-btn', {
    class: cls, dataset, text: shown, title: t('lb.editScore'), 'aria-label': `${label}: ${shown}. ${t('lb.editScore')}`,
    onclick: (e) => {
      e.stopPropagation();
      let done = false;
      const input = h('input.score-input', {
        type: 'number', inputMode: 'numeric', step: 'any', value: String(value), 'aria-label': label, class: cls,
        onkeydown: (ev) => {
          if (ev.key === 'Enter') { ev.preventDefault(); finish(true); }
          if (ev.key === 'Escape') { ev.preventDefault(); ev.stopPropagation(); finish(false); }
        },
        onblur: () => finish(true),
        onclick: (ev) => ev.stopPropagation()
      });
      function finish(commit) {
        if (done) return;
        done = true;
        const n = Number(input.value);
        const changed = commit && input.value.trim() !== '' && Number.isFinite(n) && n !== value;
        input.replaceWith(b);
        if (changed) onSet(n);
      }
      b.replaceWith(input);
      input.focus();
      input.select();
    }
  });
  return b;
}

/* ------------------------------------------------------------------ names */

/** Error message for a board title, or '' when it is fine (required + unique among all boards). */
export function boardTitleError(value, exceptId = null) {
  if (!normName(value)) return t('errors.nameRequired');
  if (store.boardTitles(exceptId).has(normName(value))) return t('errors.boardNameTaken');
  return '';
}

/** Error message for a player/team name inside a board, or '' when fine (required + unique in the board). */
export function nameInBoardError(board, value, exceptId = null) {
  if (!normName(value)) return t('errors.nameRequired');
  if (namesInBoard(board, exceptId).has(normName(value))) return t('errors.nameTaken');
  return '';
}

/**
 * Text input for a name that must stay valid. While typing, valid values are
 * committed live (onCommit) and invalid ones are only marked red; on leaving
 * the field an invalid value is reverted to the last valid one with a message.
 */
export function nameInput(props, { value, validate, onCommit }) {
  let saved = value;
  const mark = (err) => {
    input.classList.toggle('invalid', !!err);
    if (err) input.setAttribute('aria-invalid', 'true'); else input.removeAttribute('aria-invalid');
    input.title = err;
  };
  const input = h('input.input', {
    type: 'text', maxLength: 60, ...props, value,
    oninput: () => {
      const err = validate(input.value);
      mark(err);
      if (!err) { saved = input.value.trim().replace(/\s+/g, ' '); onCommit(saved); }
    },
    onchange: () => {
      const err = validate(input.value);
      if (err) toast(err, { kind: 'error' });
      input.value = saved;
      mark('');
    }
  });
  return input;
}

/* ------------------------------------------------------------- language */

export async function changeLang(code) {
  store.setSettings({ lang: code });
  await setLang(code);
  try { history.replaceState(null, '', langUrl(code).href + location.hash); } catch { /* file:// */ }
  reroute();
}

export function langSelect() {
  const sel = h('select.lang-select-input', { 'aria-label': t('settings.language'), onchange: e => changeLang(e.target.value) },
    LANGS.map(c => h('option', { value: c, text: LANG_NAMES[c] || c, selected: c === getLang() })));
  return h('label.lang-select', { title: t('settings.language'), html: icon('globe') }, sel);
}

export function themeBtn(after) {
  const b = iconBtn(resolvedScheme() === 'dark' ? 'sun' : 'moon', t('settings.toggleTheme'), () => {
    toggleScheme();
    b.innerHTML = icon(resolvedScheme() === 'dark' ? 'sun' : 'moon');
    after?.();
  });
  return b;
}

/* --------------------------------------------------------------- app bar */

export function appBar({ extra = [] } = {}) {
  return h('header.appbar',
    h('a.brand', { href: '#/', html: logoSvg }, h('span', { text: 'Punkto' })),
    h('div.spacer'),
    ...extra,
    langSelect(),
    themeBtn(),
    iconBtn('settings', t('settings.title'), openSettings)
  );
}

export function footer() {
  return h('footer.site-footer',
    h('nav.footer-links',
      h('a', { href: '#/privacy', text: t('footer.privacy') }),
      h('button.linklike', { text: isPremium() ? t('premium.activeShort') : t('premium.adFree'), onclick: openPremium }),
      h('span.muted', { text: t('footer.noTracking') })
    ),
    h('nav.footer-uses', { 'aria-label': t('uses.title') },
      h('strong', { text: t('uses.title') }),
      USE_CASES.map(slug => h('a', { href: new URL(`${slug}/`, langUrl(getLang())).href, text: t('uses.' + slug) }))
    ),
    h('nav.footer-langs', { 'aria-label': t('settings.language') },
      LANGS.map(c => h('a', { href: langUrl(c).href, hreflang: c, lang: c, text: LANG_NAMES[c], onclick: (e) => { e.preventDefault(); changeLang(c); } }))
    ),
    h('p.muted.small', { text: `Punkto ${APP_VERSION}` })
  );
}

/* -------------------------------------------------------------- settings */

export function openSettings() {
  const pref = store.getSettings().theme;
  const seg = h('div.segmented', { role: 'radiogroup', 'aria-label': t('settings.theme') },
    ['auto', 'light', 'dark'].map(v => h('button', {
      class: v === pref ? 'on' : '', role: 'radio', 'aria-checked': String(v === pref), text: t('settings.theme_' + v),
      onclick: (e) => {
        setThemePref(v);
        seg.querySelectorAll('button').forEach(b => { b.classList.toggle('on', b === e.currentTarget); b.setAttribute('aria-checked', String(b === e.currentTarget)); });
      }
    })));

  const used = store.storageUsage();
  const pct = Math.min(100, Math.round(used / (5 * 1024 * 1024) * 100));
  const content = h('div.stack',
    h('div.field', h('span.field-label', { text: t('settings.language') }), langSelect()),
    h('div.field', h('span.field-label', { text: t('settings.theme') }), seg),
    h('div.field',
      h('span.field-label', { text: t('premium.title') }),
      h('div.row',
        h('span', { class: isPremium() ? 'pill ok' : 'pill', text: isPremium() ? t('premium.activeShort') : t('premium.free') }),
        btn(isPremium() ? t('common.manage') : t('premium.adFree'), { icon: 'sparkle', cls: 'btn-ghost', onclick: () => { m.close(); openPremium(); } })
      )
    ),
    h('div.field',
      h('span.field-label', { text: t('settings.data') }),
      h('p.small.muted', { text: t('settings.dataHint') }),
      h('div.row.wrap',
        btn(t('settings.exportAll'), { icon: 'download', cls: 'btn-ghost', onclick: exportAll }),
        btn(t('settings.import'), { icon: 'upload', cls: 'btn-ghost', onclick: () => { m.close(); importFromFile(); } })
      ),
      h('div.meter', { title: `${pct}%` }, h('div.meter-fill', { style: { width: Math.max(2, pct) + '%' } })),
      h('p.small.muted', { text: t('settings.storage', { used: fmtNum(Math.round(used / 1024)), total: fmtNum(5120) }) })
    ),
    h('div.field',
      h('div.row.wrap',
        h('a.btn.btn-ghost', { href: '#/privacy', onclick: () => m.close(), html: icon('shield') }, h('span', { text: t('footer.privacy') })),
        btn(t('settings.wipe'), {
          icon: 'trash', cls: 'btn-ghost danger-text', onclick: async () => {
            if (!await confirmDialog(t('settings.wipeConfirm'), { danger: true, okLabel: t('settings.wipe') })) return;
            store.wipeAll();
            m.close();
            location.hash = '#/';
            reroute();
          }
        })
      )
    ),
    h('p.small.muted', { text: `Punkto ${APP_VERSION}` })
  );
  const m = modal({ title: t('settings.title'), content, actions: [{ label: t('common.done'), kind: 'primary' }] });
}

export function exportAll() {
  const boards = store.listBoards();
  if (!boards.length) { toast(t('home.empty')); return; }
  downloadText(`punkto-backup-${new Date().toISOString().slice(0, 10)}.json`, exportJson(boards));
}

export async function importFromFile() {
  const file = await pickFile('application/json,.json');
  if (!file) return;
  try {
    const boards = parseImport(await file.text());
    const ids = new Set(store.listBoards().map(b => b.id));
    const titles = store.boardTitles();
    for (const b of boards) {
      prepareImported(b, ids, titles);
      ids.add(b.id);
      titles.add(normName(b.title));
      store.saveBoard(b, { touch: false });
    }
    toast(t('share.imported', { n: boards.length }), { kind: 'ok' });
    reroute();
  } catch (e) {
    console.warn(e);
    toast(t('errors.badFile'), { kind: 'error' });
  }
}

/* --------------------------------------------------------------- premium */

export function openPremium() {
  const content = h('div.stack');
  const m = modal({ title: t('premium.title'), content, cls: 'premium-modal' });

  if (isPremium()) {
    const lic = getLicense();
    content.append(
      h('div.premium-ok', { html: icon('check') }, h('strong', { text: t('premium.active') })),
      h('p.muted', { text: t('premium.thanks') }),
      h('p.small.muted', { text: `${t('premium.key')}: ${maskKey(lic.key)}` }),
      btn(t('premium.remove'), {
        cls: 'btn-ghost', onclick: async () => {
          if (!await confirmDialog(t('premium.removeConfirm'))) return;
          await removeLicense();
          m.close();
          reroute();
        }
      })
    );
    return;
  }

  const status = h('p.small', { role: 'status' });
  const input = h('input.input', { type: 'text', placeholder: 'XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX', autocomplete: 'off', spellcheck: false, 'aria-label': t('premium.key') });
  const activateBtn = btn(t('premium.activate'), {
    cls: 'btn-primary', onclick: async () => {
      if (!input.value.trim()) { input.focus(); return; }
      activateBtn.disabled = true;
      status.className = 'small muted';
      status.textContent = t('premium.checking');
      try {
        await activateLicense(input.value);
        toast(t('premium.active'), { kind: 'ok' });
        m.close();
        reroute();
      } catch (e) {
        status.className = 'small error-text';
        status.textContent = t('premium.err_' + (e.code || 'invalid'));
      } finally {
        activateBtn.disabled = false;
      }
    }
  });
  input.addEventListener('keydown', e => { if (e.key === 'Enter') { e.preventDefault(); activateBtn.click(); } });

  content.append(
    h('ul.benefits', ['b1', 'b2', 'b3', 'b4'].map(k => h('li', { html: icon('check') }, h('span', { text: t('premium.' + k) })))),
    h('a.btn.btn-primary.btn-lg.block', { href: cfg.premium.checkoutUrl, target: '_blank', rel: 'noopener', html: icon('sparkle') },
      h('span', { text: t('premium.buy', { price: cfg.premium.priceLabel }) })),
    h('p.small.muted.center', { text: t('premium.payments') }),
    h('div.divider'),
    h('label.field-label', { text: t('premium.haveKey') }),
    h('div.row', input, activateBtn),
    status
  );

  if (adsActive()) {
    content.append(
      h('div.divider'),
      h('div.row.space',
        h('div', h('strong', { text: t('premium.hideSession') }), h('p.small.muted', { text: t('premium.hideSessionHint') })),
        btn(t('premium.hideSessionBtn'), { cls: 'btn-ghost', onclick: () => { hideAdsForSession(); m.close(); reroute(); } })
      )
    );
  }
}

/* ---------------------------------------------------------------- privacy */

export function privacyView(root) {
  document.title = `${t('privacy.title')} · Punkto`;
  // p7 (statistics) is only shown when statistics are switched on in config.js.
  const analyticsOn = /^[a-f0-9]{32}$/i.test(cfg.analytics?.cloudflareToken || '');
  const paras = ['p1', 'p2', 'p3', 'p4', 'p5', 'p6', analyticsOn ? 'p7' : null].filter(Boolean).map(k => h('p', { text: t('privacy.' + k) }));
  root.append(
    appBar(),
    h('main.page.prose',
      h('a.back-link', { href: '#/', html: icon('back') }, h('span', { text: t('common.back') })),
      h('h1', { text: t('privacy.title') }),
      ...paras,
      cfg.contactEmail ? h('p', {}, t('privacy.contact') + ' ', h('a', { href: 'mailto:' + cfg.contactEmail, text: cfg.contactEmail })) : null
    ),
    footer()
  );
}

/* ------------------------------------------------------- restore from link */

export function importView(root, payload) {
  root.append(appBar(), h('main.page', h('p.muted.center', { text: t('share.reading') })));
  linkToBoard(payload).then((board) => {
    const n = board.mode === 'leaderboard' ? board.players.length : board.teams.reduce((a, x) => a + x.players.length, 0);
    let done = false;
    modal({
      title: t('share.restoreTitle'),
      content: h('div.stack',
        h('p', {}, t('share.restoreText') + ' ', h('strong', { text: board.title })),
        h('p.small.muted', { text: `${t('modes.' + board.mode)} · ${t('home.players', { n })}` }),
        h('p.small.muted', { text: t('share.noImages') })
      ),
      actions: [
        { label: t('common.cancel'), kind: 'ghost' },
        {
          label: t('share.restore'), kind: 'primary', onClick: () => {
            done = true;
            prepareImported(board, new Set(store.listBoards().map(b => b.id)), store.boardTitles());
            store.saveBoard(board);
            location.replace('#/b/' + board.id);
          }
        }
      ],
      onClose: () => { if (!done) location.replace('#/'); }
    });
  }).catch((e) => {
    console.warn(e);
    toast(t('errors.badLink'), { kind: 'error' });
    location.replace('#/');
  });
}
